"""
gta_catalog.py — name<->hash catalogs + natural-language resolve + model-crash blacklist.

The "ease" layer: turns "police car" / "an ak47" / "a cop" into the exact model hash to spawn, so
Claude (or anyone) describes outcomes instead of memorizing hashes. Pure data -> paused-safe (off-thread).

Data: catalogs/{vehicles,peds,weapons}.json (generated by tools/gen_catalogs.py from SHVDN's public
hash enums) + catalogs/aliases.json (hand-curated NL -> canonical name).

Commands: resolve, catalog_search, catalog_list, catalog_categories, model_safety.
"""
import json, os

_HERE = os.path.dirname(os.path.abspath(__file__))
_DIR = os.path.join(_HERE, "catalogs")

CATALOGS = {}     # kind -> {name_lower: hash_uint}
REVERSE = {}      # kind -> {hash_uint: name}
ALIASES = {}      # kind -> {phrase: canonical_name}
ANIMS = {}        # label_lower -> {type, dict?, clip?, scenario?, flags?, prop?, bone?, label}

# Models documented to CRASH on load (SHVDN NativeMemory.cs stub list). A wrong/stub model hash
# crashes the game on CREATE_* — refuse these the same way the native allowlist refuses bad hashes.
KNOWN_CRASH_HASHES = {
    0xA71D0D4F: "astron2", 0x170341C2: "cyclone2",
}

def _jenkins(s):
    h = 0
    for c in s.lower():
        h = (h + ord(c)) & 0xFFFFFFFF
        h = (h + (h << 10)) & 0xFFFFFFFF
        h ^= (h >> 6)
    h = (h + (h << 3)) & 0xFFFFFFFF
    h ^= (h >> 11)
    h = (h + (h << 15)) & 0xFFFFFFFF
    return h

def _load():
    CATALOGS.clear(); REVERSE.clear(); ALIASES.clear()
    for kind in ("vehicles", "peds", "weapons"):
        p = os.path.join(_DIR, f"{kind}.json")
        if os.path.exists(p):
            with open(p, "r", encoding="utf-8") as f:
                d = {k: int(v) & 0xFFFFFFFF for k, v in json.load(f).items() if not k.startswith("$")}
            CATALOGS[kind] = d
            REVERSE[kind] = {v: k for k, v in d.items()}
    ap = os.path.join(_DIR, "aliases.json")
    dropped = 0
    if os.path.exists(ap):
        with open(ap, "r", encoding="utf-8") as f:
            raw = json.load(f)
        for kind in ("vehicles", "peds", "weapons"):
            valid = {}
            for k, v in raw.get(kind, {}).items():
                if k.startswith("$"):
                    continue
                # Only keep aliases whose target is a real catalog key (else they'd silently mislead).
                if v.lower() in CATALOGS.get(kind, {}):
                    valid[k.lower()] = v.lower()
                else:
                    dropped += 1
            ALIASES[kind] = valid
    ANIMS.clear()
    anp = os.path.join(_DIR, "anims.json")
    if os.path.exists(anp):
        with open(anp, "r", encoding="utf-8") as f:
            for k, v in json.load(f).get("anims", {}).items():
                if not k.startswith("$"):
                    ANIMS[k.lower()] = v
    return {"vehicles": len(CATALOGS.get("vehicles", {})),
            "peds": len(CATALOGS.get("peds", {})),
            "weapons": len(CATALOGS.get("weapons", {})),
            "anims": len(ANIMS),
            "aliases": sum(len(a) for a in ALIASES.values()),
            "aliases_dropped": dropped}

_SUMMARY = _load()

def _kinds(kind):
    return [kind] if kind in CATALOGS else list(CATALOGS.keys())

def resolve(name, kind=None):
    """NL/name -> {kind, name, hash, hex, crash_warning?, alternatives?}. Resolution order:
    alias -> exact catalog name -> unique substring -> JOAAT the raw string (last resort)."""
    if name is None:
        return {"error": "no name given"}
    q = str(name).strip().lower()
    searched = _kinds(kind)
    # 1) alias (natural language)
    for k in searched:
        canon = ALIASES.get(k, {}).get(q)
        if canon and canon in CATALOGS.get(k, {}):
            return _hit(k, canon, "alias")
    # 2) exact catalog name
    for k in searched:
        if q in CATALOGS.get(k, {}):
            return _hit(k, q, "exact")
    # 3) substring (prefer the shortest, most specific name; report alternatives)
    cands = []
    for k in searched:
        for n in CATALOGS.get(k, {}):
            if q in n:
                cands.append((k, n))
    if cands:
        cands.sort(key=lambda kn: (len(kn[1]), kn[1]))
        k, n = cands[0]
        out = _hit(k, n, "substring")
        if len(cands) > 1:
            out["alternatives"] = [{"kind": kk, "name": nn} for kk, nn in cands[1:9]]
        return out
    # 4) JOAAT fallback (covers names not in our catalog — still a valid model hash)
    h = _jenkins(q)
    return {"kind": kind or "unknown", "name": q, "hash": h, "hex": f"0x{h:X}",
            "match": "joaat", "note": "not in catalog; hashed the raw name (verify it's a real model)",
            "crash_warning": h in KNOWN_CRASH_HASHES}

def _hit(kind, name, match):
    h = CATALOGS[kind][name]
    out = {"kind": kind, "name": name, "hash": h, "hex": f"0x{h:X}", "match": match}
    if h in KNOWN_CRASH_HASHES:
        out["crash_warning"] = "model is documented to CRASH on load - do not spawn"
    return out

def search(query, kind=None, limit=25):
    q = str(query or "").strip().lower()
    res = []
    for k in _kinds(kind):
        for n, h in CATALOGS.get(k, {}).items():
            if q in n:
                res.append({"kind": k, "name": n, "hex": f"0x{h:X}"})
    res.sort(key=lambda r: (len(r["name"]), r["name"]))
    return {"success": True, "query": q, "count": len(res), "results": res[:limit]}

# ---- handlers ----
def handle_resolve(p):       return resolve(p.get("name"), p.get("kind"))
def handle_catalog_search(p): return search(p.get("query"), p.get("kind"), p.get("limit", 25))
def handle_catalog_categories(p):
    return {"success": True, "aliases": {k: sorted(v.keys()) for k, v in ALIASES.items()}}
def handle_catalog_list(p):
    kind = p.get("kind", "vehicles"); off = p.get("offset", 0); lim = p.get("limit", 50)
    names = sorted(CATALOGS.get(kind, {}).keys())
    return {"success": True, "kind": kind, "total": len(names), "names": names[off:off+lim]}
def handle_model_safety(p):
    h = p.get("hash")
    if isinstance(h, str): h = int(h, 16) if h.lower().startswith("0x") else int(h)
    h = int(h) & 0xFFFFFFFF if h is not None else None
    return {"success": True, "hash": f"0x{h:X}" if h is not None else None,
            "safe": h not in KNOWN_CRASH_HASHES,
            "crash_blacklist": {f"0x{k:X}": v for k, v in KNOWN_CRASH_HASHES.items()}}
def handle_catalog_status(p):
    return {"success": True, **_SUMMARY, "crash_blacklisted": len(KNOWN_CRASH_HASHES)}

def anim_search(query, limit=15):
    q = str(query or "").strip().lower()
    res = [{"key": k, **v} for k, v in ANIMS.items() if not q or q in k or q in str(v.get("label", "")).lower()]
    res.sort(key=lambda r: r["key"])
    return {"success": True, "query": q, "count": len(res), "results": res[:limit]}
def handle_anim_search(p): return anim_search(p.get("query"), p.get("limit", 15))
def handle_anim_get(p):
    q = str(p.get("name") or "").strip().lower()
    if q in ANIMS:
        return {"success": True, "key": q, **ANIMS[q]}
    for k, v in ANIMS.items():
        if q and (q in k or q in str(v.get("label", "")).lower()):
            return {"success": True, "key": k, **v}
    return {"error": f"no anim '{q}'", "hint": "anim_search to list; or use the full alexguirre animations-list"}

CAT_COMMANDS = {
    "resolve": handle_resolve, "catalog_search": handle_catalog_search,
    "catalog_categories": handle_catalog_categories, "catalog_list": handle_catalog_list,
    "model_safety": handle_model_safety, "catalog_status": handle_catalog_status,
    "anim_search": handle_anim_search, "anim_get": handle_anim_get,
}
CAT_OFFTHREAD = set(CAT_COMMANDS.keys())   # pure data -> all paused-safe

if __name__ == "__main__":
    import sys
    try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception: pass
    print("loaded:", _SUMMARY)
    for t in ("police car", "adder", "ak47", "a cop", "buzzard", "nonexistentxyz"):
        print(f"  resolve({t!r}) ->", resolve(t))
    print("  search('police', 'vehicles'):", search("police", "vehicles", 5)["count"], "hits")
