"""
gta_recipes.py — queryable "how GTA V actually works" recipes (the distilled PATTERNS cards).

Lets a bridge client ask "how do I attach a prop to a bone?" / "spawn on the ground" and get the
verified problem->method->gotcha card, with the source mod. Pure data -> paused-safe (off-thread).

Data: recipes/recipes.json (generated by tools/gen_recipes.py from Examples/PATTERNS/*.md).
Commands: recipe_search, recipe_get, recipe_categories, recipe_count.
"""
import json, os

_HERE = os.path.dirname(os.path.abspath(__file__))
_PATH = os.path.join(_HERE, "recipes", "recipes.json")
RECIPES = []

def _load():
    global RECIPES
    if os.path.exists(_PATH):
        with open(_PATH, "r", encoding="utf-8") as f:
            RECIPES = json.load(f).get("recipes", [])
    return len(RECIPES)

_N = _load()

_FIELDS = ("title", "problem", "method", "gotcha", "category", "source")
_STOP = {"a", "an", "the", "to", "of", "on", "in", "for", "and", "or", "how", "do", "i",
         "with", "my", "is", "it", "via", "by", "from", "into", "at", "as", "this"}

def search(query, category=None, limit=8):
    """Rank recipes by how many query terms hit their text (title/category weighted; stopwords ignored)."""
    terms = [t for t in str(query or "").lower().split() if t and t not in _STOP]
    out = []
    for r in RECIPES:
        if category and category.lower() not in r.get("category", "").lower():
            continue
        hay = " ".join(str(r.get(f, "")) for f in _FIELDS).lower()
        if not terms:
            score = 0
        else:
            score = sum(hay.count(t) for t in terms)
            # weight title/category hits higher
            title = (r.get("title", "") + " " + r.get("category", "")).lower()
            score += 3 * sum(1 for t in terms if t in title)
            if score == 0:
                continue
        out.append((score, r))
    out.sort(key=lambda sr: -sr[0])
    return {"success": True, "query": query, "count": len(out),
            "results": [_brief(r) for _, r in out[:limit]]}

def _brief(r):
    return {"id": r.get("id"), "title": r.get("title"), "category": r.get("category"),
            "problem": r.get("problem"), "method": r.get("method"), "gotcha": r.get("gotcha"),
            "source": r.get("source"), "file": r.get("file")}

def get(rid):
    for r in RECIPES:
        if r.get("id") == rid:
            return {"success": True, **_brief(r), "corroboration": r.get("corroboration")}
    # fuzzy: title substring
    q = str(rid or "").lower()
    for r in RECIPES:
        if q and q in r.get("title", "").lower():
            return {"success": True, **_brief(r)}
    return {"error": f"no recipe '{rid}'"}

# ---- handlers ----
def handle_recipe_search(p): return search(p.get("query"), p.get("category"), p.get("limit", 8))
def handle_recipe_get(p):    return get(p.get("id"))
def handle_recipe_categories(p):
    cats = {}
    for r in RECIPES:
        c = r.get("category", "?")
        cats[c] = cats.get(c, 0) + 1
    return {"success": True, "total": len(RECIPES),
            "categories": dict(sorted(cats.items(), key=lambda kv: -kv[1]))}
def handle_recipe_count(p):  return {"success": True, "count": len(RECIPES)}

REC_COMMANDS = {
    "recipe_search": handle_recipe_search, "recipe_get": handle_recipe_get,
    "recipe_categories": handle_recipe_categories, "recipe_count": handle_recipe_count,
}
REC_OFFTHREAD = set(REC_COMMANDS.keys())   # pure data -> all paused-safe

if __name__ == "__main__":
    import sys
    try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception: pass
    print("loaded recipes:", _N)
    for q in ("attach prop to bone", "spawn on ground", "vector3 return", "scaleform string", "wheel camber"):
        hits = search(q, limit=2)["results"]
        print(f"  search({q!r}) -> {[h['title'][:48] for h in hits]}")
    print("  categories:", handle_recipe_categories({})["categories"])
